<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-31 07:34
=======
# Generated by Django 5.0.1 on 2024-01-31 07:10
>>>>>>> 1ed46a4feee1fa15cc9b28619c7b1764d264a5ea

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

<<<<<<< HEAD
    dependencies = [
    ]
=======
    dependencies = []
>>>>>>> 1ed46a4feee1fa15cc9b28619c7b1764d264a5ea

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode/')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("employee", "Employee")],
                        default="employee",
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "barcode",
                    models.ImageField(blank=True, null=True, upload_to="barcode/"),
                ),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
>>>>>>> 1ed46a4feee1fa15cc9b28619c7b1764d264a5ea
            },
        ),
    ]
