# Generated by Django 5.0.1 on 2024-01-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
